#+TITLE: alpha策略的分类

alpha模型是量化交易模型的核心。通过对alpha策略的研究，才有可能获得与市场波动无关的回报。
本文根据alpha策略的内在属性，总结了alpha策略不同角度的分类方法。

* alpha策略

alpha回报是指扣除市场基准回报之后的投资回报，反映了投资者决策的价值。

* alpha策略的分类方法

** 按研究方法

  我们进行科学研究有两种主要的方法：理论推导（演绎法）和经验总结（归纳法）。

  理论推导方法在合理假设的基础上，提出用于解释事物的模型，对模型进行严格的数学推导，
  可以得出各种推论。如果经过实践检验没有证伪模型及其推论，则可以认为理论是正确的，
  并且基于理论可以对现实进行预测。

  经验总结方法认为对现实世界经过足够多的观察，也可以总结出规律。尽管没有严格的理论推导，
  但这些总结出来的经验依然可以预测现实。在进行归纳总结时，可以依靠统计学方法，使得从数据
  到结论的过程更加科学合理。而新兴的数据分析和挖掘、机器学习、深度学习等方法，可以极大
  降低对专业知识的要求，提高归纳总结的效率。

  对应到alpha策略，根据其研究方法也可以分为理论型和经验型。

  理论型的alpha从某种经济学理论对市场行为的解释出发，构建模型并用市场数据检验模型预测的
  准确性。根据市场理论的不同，理论型lapha模型
  大体可以分为趋势型(trend)，回复型(reversion),价值/收益型(value/yield)，
  成长型(growth)，品质型(quality)五种类型。

 
*** 趋势型
    
趋势型策略也成为动量策略。其市场假设是：

#+BEGIN_QUOTE

#+END_QUOTE

*** 回复型

*** 价值/收益型

*** 成长型

*** 品质型

** 按输入数据

   不管是理论型还是经验型alpha模型，都需要根据输入的数据预测市场行为。
   根据输入数据的不同，可以将alpha模型分为市场数据驱动和基本面数据驱动两类。

   比如，趋势型、回复型模型以市场数据作为输入；而价值/收益型、成长型和品质型模型
   以基本面数据作为输入。

- 需要的数据
  其中，趋势型和回复型需要价格数据作为数据；其他三种需要基本面数据作为输入。

* 输入类型

* 常见策略

|   | 模型驱动 | 输入类型 |   |   |
|---+----------+----------+---+---|
|   |          |          |   |   |

* alpha
** abc
*** def
** 2
