#+TITLE: alpha策略的分类

alpha模型是量化交易模型的核心。通过对alpha策略的研究，才有可能获得与市场波动无关的回报。
本文根据alpha策略的内在属性，总结了alpha策略不同角度的分类方法。

* alpha策略

alpha回报是指扣除市场基准回报之后的投资回报，反映了投资者决策的价值。

* alpha策略的分类方法

** 按研究方法

  我们进行科学研究有两种主要的方法：理论推导（演绎法）和经验总结（归纳法）。

  理论推导方法在合理假设的基础上，提出用于解释事物的模型，对模型进行严格的数学推导，
  可以得出各种推论。如果经过实践检验没有证伪模型及其推论，则可以认为理论是正确的，
  并且基于理论可以对现实进行预测。

  经验总结方法认为对现实世界经过足够多的观察，也可以总结出规律。尽管没有严格的理论推导，
  但这些总结出来的经验依然可以预测现实。在进行归纳总结时，可以依靠统计学方法，使得从数据
  到结论的过程更加科学合理。而新兴的数据分析和挖掘、机器学习、深度学习等方法，可以极大
  降低对专业知识的要求，提高归纳总结的效率。

  对应到alpha策略，根据其研究方法也可以分为理论型和经验型。

  理论型的alpha从某种经济学理论对市场行为的解释出发，构建模型并用市场数据检验模型预测的
  准确性。根据市场理论的不同，理论型lapha模型
  大体可以分为趋势型(trend)，回复型(reversion),价值/收益型(value/yield)，
  成长型(growth)，品质型(quality)五种类型。

 
*** 趋势型
    
趋势型策略也称为动量策略。其市场假设是：

#+BEGIN_QUOTE
趋势一旦形成，就会延续一段时间，直到形成新的趋势为止。如果能够识别出趋势并跟随，就能够获利。
#+END_QUOTE

对于趋势策略的经济学解释，有“部分有效市场假说”，“博傻理论”等。

趋势型策略的关键在于对于趋势确立的判断。比如经典的“双均线”模型。

越早判断出趋势，获利的空间越大，但判断错误的风险也越大。所以，趋势型策略还要分析可能的风险和
可能的收益之间的比例，来决定是否进行操作。在操作开始之前，就要设置好止损的策略，避免过大的损失。

*** 回复型
回复型策略的市场假设是：

#+BEGIN_QUOTE

价格围绕某个中心波动，如果能够识别出这个中心并判断出波动的幅度，就有可能从中获利。
一般来说，回复型策略是“逆趋势策略”，或称为“反转交易”。

#+END_QUOTE

根据波动中心或者波动幅度的不同定义，可以有不同的回复型策略，比如“均值回复策略”，
“超买/超卖(over-bought/over-sold)”策略，“背离策略”等。

最著名的回复策略如统计套利：两只相似的股票，其价格偏差会在一定浮动内来回波动。

*** 价值/收益型

价值型策略研究某种基本面因素和股票价格之间的比率关系。并从比率失衡中寻找获利机会。

比如，市盈率(P/E,price-to-earning).

一般在模型处理上，以价格作为分母，作为某种收益率指标，这样便于分析的简单和一致。
比如，盈利收益率(earnings yield, = E/P), 股利收益率(dividend yield)等。
不难看出，收益率越高的股票，则其目前的价格相对来说越便宜。

市净率(book value to price), 息税折旧前收益(EBITDA)/企业价值(EV)

即使基于相同的收益率指标，也可以给出不同的策略。比如：

可以买入相对便宜的产品;

可以买入风险高的产品，卖出风险低的产品。（其理论认为，风险高的产品，其预期收益也会更高）;

携带交易(carry trade): 基于一个相对价差，买入价值相对低估的股票同时卖出价格相对高估的股票。

*** 成长型
P54
*** 品质型
P56
** 按输入数据

   不管是理论型还是经验型alpha模型，都需要根据输入的数据预测市场行为。
   根据输入数据的不同，可以将alpha模型分为市场数据驱动和基本面数据驱动两类。

   比如，趋势型、回复型模型以市场数据作为输入；而价值/收益型、成长型和品质型模型
   以基本面数据作为输入。

- 需要的数据
  其中，趋势型和回复型需要价格数据作为数据；其他三种需要基本面数据作为输入。

** 按交易频率

超高频，高频，中频，低频

** 按投注结构

绝对，相对

** 按流动性

流动性好，流动性差

* 混合策略

* 常见策略

|   | 模型驱动 | 输入类型 |   |   |
|---+----------+----------+---+---|
|   |          |          |   |   |

* alpha
** abc
*** def
** 2
